# Generated by Django 5.0.6 on 2024-05-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_alter_like_unique_together_like_unique_like'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='likes',
        ),
    ]
