# Generated by Django 5.0.6 on 2024-05-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_alter_area_table'),
        ('country', '0003_alter_country_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('name', 'country')},
        ),
    ]
