version: '3.8'

services:
  # postgres db
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django
    volumes:
      - postgres_data_django:/var/lib/postgresql/data
    networks:
      - app-network_django

networks:
  app-network_django:

volumes:
  postgres_data_django:
