# Generated by Django 5.0.6 on 2024-05-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_alter_permission_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rolepermission',
            table='role_permissions',
        ),
    ]
