# Generated by Django 5.0.6 on 2024-05-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_alter_country_name'),
        ('roles', '0002_alter_userrole_unique_together_alter_role_table_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'country')},
        ),
    ]
